### ISSUE TITLE
Improve loop rendering

### ISSUE THREAD

**Issue by dodie** [dodie/scott#18]
When a loop body is executed multiple times, Scott records and prints variable states from every turn:

```
  47|      @Test
  48|      public void test() throws Exception {
  49|          int i = 0;  // i=0
  50|          while (i < 10) {
  51|              i = i + 1;  // i=1
    |                          // i=2
    |                          // i=3
    |                          // i=4
    |                          // i=5
    |                          // i=6
    |                          // i=7
    |                          // i=8
    |                          // i=9
    |                          // i=10
  52|          }
  53|*         fail();  // AssertionError
  54|      }
```

This looks really boring, and should be enhanced.

Maybe print the first and the last few only with the number of the corresponding turn; or simply show the last recorded value?

**Comment by basalt79** [comment]
@dodie, I can take this if it ok for you!

**Comment by dodie** [comment]
@basalt79, ok! :+1:

**Comment by basalt79** [comment]
i am working on 3 versions.
version 1: (full size indicator in front)
```
  25|          while (i < 10) {
  26|              i++;  // i=[10] 1;2;3...;8;9;10
```
version 2: (full size indicator in middle)
```
  25|          while (i < 10) {
  26|              i++;  // i=1;2;3...[10]...;8;9;10
```
version 3: (no full size indicator)
```
  25|          while (i < 10) {
  26|              i++;  // i=1;2;3...;8;9;10
```

Example with multi variables per line
```
  15|          while (i < 10) {
  16|              i++; int a = 5;  // a=5
    |                               // i=[10] 1;2;3...;8;9;10
```
the amount of start and end numbers (in the scenarios above = 3) can be changed easy.
@dodie feel free to add your opinion on this.

**Comment by dodie** [comment]
I think version 2 is a bit confusing, but version 1 and 3 looks reasonable. Indicating the last value is a really cool idea.

What do you think about the combination of version 1 and 3?

```
  25|          while (i < 10) {
  26|              i++;  // i=1;2;3...;8;9;[10]
```

It lists all elements and highlights the last value. It's simpler because it does not display the last element twice, but I am not sure that this combined presentation does not confuse the users.

**Comment by basalt79** [comment]
Hi

The information in brackets [] is not the last value, its the count, the number of values
```
int i = 0;  // i=0
  15|          while (i < 20) {
  16|              i+=2;  // i=2;4;6...;16;18;20 [10] 
  17|           
```
So in your version "// i=1;2;3...;8;9;[10]" the information about the loop count gets lost.

**Comment by dodie** [comment]
I see, in this case it doesn't make any sense to combine version 1 and 3. :)
With this in mind however, I think the count indicator should be after the values, as it's generally less important.

**Comment by basalt79** [comment]
we can try 
```
int i = 0;  // i=0
  15|          while (i < 20) {
  16|              i+=2;  // i=2;4;6...;16;18;[20] =>10 
  17|           
```
so the [20] is now highlighted as last value
and the => 10 defines the loop count

**Comment by dodie** [comment]
Ok, this looks fine to me.

**Comment by dodie** [comment]
Great job, thanks @basalt79 !
