### ISSUE TITLE
Add support for TestNG

### ISSUE THREAD

**Issue by dodie** [dodie/scott#21]
Scott supports JUnit4 and 5, but It would be nice to support TestNG as well.

To achieve this, the system has to be extended in at least the following places:

- [This](https://github.com/dodie/scott/blob/master/scott/src/main/java/hu/advancedweb/scott/instrumentation/transformation/param/TestDiscoveryMethodVisitor.java) class is responsible to determine what methods should be instrumented to track behavior. This should be modified to mark TestNG methods as well.
- The same class is responsible to determine what classes should be instrumented with integration to the test framework. For example in the case of JUnit4, it marks a class to be injected with a [ReportingRule](https://github.com/dodie/scott/blob/master/scott/src/main/java/hu/advancedweb/scott/runtime/ScottReportingRule.java) it the class contains a ```@Test``` method. Similarly to the first point, this should be augmented to handle TestNG code.
- Finally, the instrumentation part of the code has to be extended to inject TestNG specific code to the tests (marked by the previous point) to handle failing test cases and print the report. See ```visitMethod``` and ```visitEnd``` in [this](https://github.com/dodie/scott/blob/97dbe324e8a2f0bd0a1807ae5e19cad36082e4d2/scott/src/main/java/hu/advancedweb/scott/instrumentation/transformation/StateTrackingTestClassVisitor.java#L39) class to see how it's handled for the JUnit4 Reporting Rule.

For more info about the architecture, please see the [development guide](https://github.com/dodie/scott/blob/master/docs/development-guide.md).

**Comment by dodie** [comment]
Moved to the [idea list in wiki](https://github.com/dodie/scott/wiki/Ideas).

**Comment by geofflangenderfer** [comment]
I believe TestDiscoveryMethodVisitor was renamed to [DiscoveryMethodVisitor](https://github.com/dodie/scott/blob/4.0.1/scott/src/main/java/hu/advancedweb/scott/instrumentation/transformation/param/DiscoveryMethodVisitor.java)

**Comment by dodie** [comment]
Hi @geofflangenderfer,

Yes, `TestDiscoveryMethodVisitor` was renamed to `DiscoveryMethodVisitor` as part of an API stabilization when new configuration options were introduced. May I ask where did you bump into the old name? I'd be happy to clean up obsolete documentation.

Cheers,
Dávid

**Comment by geofflangenderfer** [comment]
I was thinking about using scott with testng. This is one of the first roadblocks I ran into. I thought I would share my findings for the next person. Hopefully I have time at some point to look at this.
