### ISSUE TITLE
Show differences 

### ISSUE THREAD

**Issue by basalt79** [dodie/scott#32]
```	
@Test
public void test_3() {
    String empty = "";
    String first = "1";
    String last = "2";
    String concatenated = empty + first + last;
    assertEquals(12, concatenated);
}
```
will lead to
```
java.lang.AssertionError: 
  29|      @Test
  30|      public void test_3() {
  31|          String empty = "";  // empty=
  32|          String first = "1";  // first=1
  33|          String last = "2";  // last=2
  34|          String concatenated = empty + first + last;  // concatenated=12
  35|*         assertEquals(12, concatenated);  // AssertionError: expected: java.lang.Integer<12> but was: java.lang.String<12>
  36|      }
 <Click to see difference>
```

after click "Click to see difference" link at Intellij, the diff will be reported as

![view_difference](https://user-images.githubusercontent.com/10912019/31053422-16aa2ae2-a69d-11e7-8144-9cabff84ea73.png)

as you can see, there is also the " 36|      }" shown as difference

**Comment by dodie** [comment]
Nice find! I am not sure what can be done about it, my guess is that IDEs use various heuristics in an attempt to extract info from common assertion messages, and they don't like if the messages are manipulated.

Could you please check if adding an empty line after the Exception in the report solves the problem? ([This](https://github.com/dodie/scott/blob/master/scott/src/main/java/hu/advancedweb/scott/runtime/report/FailureRenderer.java#L196) is the part of the rendering logic that is responsible for printing the exception.)

**Comment by basalt79** [comment]
all empty newlines after the exception will be shown in the diff, so this will not work.

**Comment by dodie** [comment]
I'm afraid that this problem can't be solved on our part, but I'll keep this issue open for a while, maybe we can come up with a solution later.

**Comment by dodie** [comment]
The problem still exists, however, I found no way to work around the issue. I'm closing this as a "won't fix".
