### ISSUE TITLE
Use release version of the JUnit5 dependency in the JUnit5 tests and JUnit5 example modules

### ISSUE THREAD

**Issue by dodie** [dodie/scott#37]
See this modules:
- [JUnit5 tests](https://github.com/dodie/scott/tree/master/scott-tests/junit5-tests)
- [JUnit5 examples](https://github.com/dodie/scott/tree/master/scott-examples/junit5)

**Comment by vpondala** [comment]
Can I take this one?

**Comment by dodie** [comment]
Of course!

**Comment by vpondala** [comment]
Submitted PR #38. Please review and let me know if it looks ok.

**Comment by dodie** [comment]
Looks great, thank you!
