### ISSUE TITLE
Add parameterization for the Maven Plugin

### ISSUE THREAD

**Issue by dodie** [dodie/scott#39]
Scott can be [configured](https://github.com/dodie/scott/blob/master/docs/usage.md#configuration) in various ways to fine-tune its behavior. For example, to decide what methods to instrument and what kind of error reporting mechanisms to inject to the tests.

Currently, the only way to fiddle with these parameters is to pass them as Java arguments. For example:

```
mvn clean install -Dscott.track.method_annotation="org.jsunit.Test,cucumber.api.java.*"
```

The [Scott Maven Plugin](https://github.com/dodie/scott/blob/master/docs/usage.md#recommended-scott-maven-plugin) should be able to receive these optional parameters, and if given, pass them to Scott.

Currently, the maven plugin can be set up like the following: (see [this](https://github.com/dodie/scott/tree/master/scott-examples/junit4) for a working example)

```xml
<plugin>
	<groupId>hu.advancedweb</groupId>
	<artifactId>scott-maven-plugin</artifactId>
	<version>3.1.0</version>
	<executions>
		<execution>
			<goals>
				<goal>prepare-agent</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

The goal of this issue to let the user provide additional configuration options, for example like this:

```xml
<plugin>
	<groupId>hu.advancedweb</groupId>
	<artifactId>scott-maven-plugin</artifactId>
	<version>3.1.0</version>
	<executions>
		<execution>
			<goals>
				<goal>prepare-agent</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<trackMethodAnnotations>
			<trackMethodAnnotation>org.junit.Test</trackMethodAnnotation>
			<trackMethodAnnotation>org.junit.jupiter.api.Test</trackMethodAnnotation>
		</trackMethodAnnotations>
		<injectJunit4RuleMethodAnnotations>
			<injectJunit4RuleMethodAnnotation>org.junit.Test</injectJunit4RuleMethodAnnotation>
		</injectJunit4RuleMethodAnnotations>
	</configuration>
</plugin>
```

The configuration options should be optional, if a configuration property is not set, it should not be passed to Scott.

To achieve this the [mojo](https://github.com/dodie/scott/blob/master/scott-maven-plugin/src/hu/advancedweb/maven/ScottAgentMojo.java) has to be enhanced to take parameters and pass them to Scott (see the ```getArgument``` method.)

**Comment by vpondala** [comment]
Never worked on a Maven plugin, let me take this one.

**Comment by dodie** [comment]
Sure!

**Comment by dodie** [comment]
I've merged a PR related to this issue, but please, if you already started working on this feel free to submit the PR.
