### ISSUE TITLE
Support for cucumber-jvm version 2.x

### ISSUE THREAD

**Issue by olpau** [dodie/scott#45]
At the moment scott is not working with cucumber version 2.x because of the changed packages:

java.lang.NoClassDefFoundError: cucumber/runtime/formatter/ColorAware

e.g. is now in cucumber-jvm: cucumber/api/formatter/ColorAware

Are there any plans to support cucumber-jvm version 2.x out of the box?

**Comment by dodie** [comment]
Yes, definitely! Unfortunately, most of the Cucumber API has changed in the new version so I think we have to provide a new set of custom formatters for the 2.x.

Just to be sure, are you using the following Cucumber dependencies?
```
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>2.3.1</version>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>2.3.1</version>
</dependency>
```

Thanks,
David

**Comment by olpau** [comment]
>Just to be sure, are you using the following Cucumber dependencies?
correct.

**Comment by dodie** [comment]
Hey @olpau ,
the next release of Scott will support cucumber `io.cucumber`. Stay tuned!
Cheers,
David
