### ISSUE TITLE
Add test for Local Variable Type Inference

### ISSUE THREAD

**Issue by dodie** [dodie/scott#47]
Enhance the test suite to verify that variables in tests containing `var` keywords are correctly recorded. Similar tests can be found in the [junit4-tests](https://github.com/dodie/scott/tree/master/scott-tests/junit4-tests) project. For more info about Local Variable Type Inference, see [JEP 286](http://openjdk.java.net/jeps/286) and [JEP 323](http://openjdk.java.net/jeps/323).

Also, add a failing test to the [showcase project](https://github.com/dodie/scott/tree/master/scott-examples/junit4), to make sure that the rendered failure message looks pretty.

Note: please make sure to visit the [contribution](https://github.com/dodie/scott/tree/master/CONTRIBUTING.md) and [development guide](https://github.com/dodie/scott/tree/master/docs/development-guide.md) for some important notes on how to build and debug Scott.

**Comment by vpondala** [comment]
I will work on this.

**Comment by dodie** [comment]
Awesome! 👍

**Comment by vpondala** [comment]
Hi David

I had a bit of trouble with Jdk 11 on my Dev environment. I could not
progress much on this one.

My apologies :(

**Comment by dodie** [comment]
Sure, no problem. :)

**Comment by vpondala** [comment]
I'm having trouble with maven plugin compatibility with JDK 11. Let me work on this and keep you posted.

**Comment by dodie** [comment]
Sure! Thanks for piloting the JDK 11 support!

**Comment by dodie** [comment]
Hi @vpondala!
I am planning to release the next version of Scott soon, so I've added the necessary changes regarding this issue, to make the next version Java 11 compatible.
Cheers,
David

**Comment by vpondala** [comment]
Great stuff. Sorry for the delay.
