### ISSUE TITLE
Eliminate leftovers from the old Java 6 support

### ISSUE THREAD

**Issue by dodie** [dodie/scott#78]
Core Scott components are compatible with Java 7+, but the original version of the plugin was built with Java 6 compatibility in mind. Because of this, Java 7 features are not used in many parts of the codebase.

Clean up the codebase to use Java 7 features where appropriate. Avoid using features available from Java 8 or later.

**Comment by imavroukakis** [comment]
👋 I'd like to have a go at this if that's ok?

**Comment by dodie** [comment]
Sure!

**Comment by imavroukakis** [comment]
🖖
